device: cuda
env_name: HalfCheetah-v3
seed: 1234
eval_seed: 2000
batch_size: 256
max_timesteps: 2000000
eval_freq: 50000
eval_episodes: 5
actor_lr: 1e-5
expert_datasize: 3000
save_model: True
lr_decay: True
lr_decay_freq: 10000
lr_decay_gamma: 0.9